[package]
name = "matinee-frontend"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
wasm-bindgen = "0.2.79"
wasm-bindgen-futures = "0.4.29"
web-sys = "0.3.56"
js-sys = "0.3.56"